import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/common/Header";
import Footer from "../components/common/Footer";
import Infobar from "../components/common/Infobar";


export const metadata: Metadata = {
  title: "Soundrich Hearing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Infobar/>
        <Header/>
        
        {children}
        
        <Footer/>
        </body>
    </html>
  );
}
